# -*- coding: utf-8 -*-
"""exercicio_20240209.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gebOKCVpds9Cgy_6_g7y3qKpNfykEFCn
"""

r = int()
x = int()
contador = int()
for x in range(1,5):
  x = int(input("Digite um numero para multiplicar por 12: "))
  r = x*12
  print("Resultado é: ",r)

